import 'package:intl/intl.dart';
import '../models/notes_data.dart';

/// Service for generating notes reports in Markdown format
/// Supports separate English and German exports
class NotesStatisticsMarkdownService {
  /// Generate English notes markdown
  static String generateEnglishMarkdown({
    required List<NoteItem> notes,
  }) {
    return _generateMarkdown(notes, isGerman: false);
  }

  /// Generate German notes markdown
  static String generateGermanMarkdown({
    required List<NoteItem> notes,
  }) {
    return _generateMarkdown(notes, isGerman: true);
  }

  static String _generateMarkdown(List<NoteItem> notes,
      {required bool isGerman}) {
    final buffer = StringBuffer();
    final stats = _calculateStatistics(notes);
    final byType = _groupByType(notes);

    // Sort notes by creation date (newest first)
    final sortedNotes = notes.toList()
      ..sort((a, b) => b.createdAt.compareTo(a.createdAt));

    // Header
    buffer.writeln(isGerman ? '# Notizen-Bericht' : '# Notes Report');
    buffer.writeln();
    buffer.writeln(isGerman
        ? '**Erstellt am:** ${DateFormat('dd.MM.yyyy HH:mm').format(DateTime.now())}'
        : '**Generated on:** ${DateFormat('MMMM dd, yyyy HH:mm').format(DateTime.now())}');
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    // Summary
    _writeSummary(buffer, stats, isGerman);
    buffer.writeln();

    // Notes by Type
    _writeNotesByType(buffer, byType, isGerman);
    buffer.writeln();

    // All Notes List
    _writeAllNotes(buffer, sortedNotes, isGerman);
    buffer.writeln();

    // Statistics
    _writeStatistics(buffer, stats, isGerman);
    buffer.writeln();

    // Footer
    buffer.writeln('---');
    buffer.writeln();
    buffer.writeln(isGerman
        ? '*Generiert von MyJob - Bewerbungsmanagement*'
        : '*Generated by MyJob - Application Management*');
    buffer.writeln();
    buffer.writeln(isGerman
        ? '**Legende:** 🔴 Dringend | 🟠 Hoch | 🟡 Mittel | 🔵 Niedrig | ✅ Erledigt | 📌 Aktiv | 📦 Archiviert'
        : '**Legend:** 🔴 Urgent | 🟠 High | 🟡 Medium | 🔵 Low | ✅ Completed | 📌 Active | 📦 Archived');

    return buffer.toString();
  }

  static Map<String, dynamic> _calculateStatistics(List<NoteItem> notes) {
    final total = notes.length;
    final active =
        notes.where((n) => !n.completed && !n.archived).length;
    final completed =
        notes.where((n) => n.completed && !n.archived).length;
    final archived = notes.where((n) => n.archived).length;

    final todos = notes.where((n) => n.type == NoteType.todo).length;
    final companyLeads =
        notes.where((n) => n.type == NoteType.companyLead).length;
    final generalNotes =
        notes.where((n) => n.type == NoteType.generalNote).length;
    final reminders = notes.where((n) => n.type == NoteType.reminder).length;

    final low = notes.where((n) => n.priority == NotePriority.low).length;
    final medium =
        notes.where((n) => n.priority == NotePriority.medium).length;
    final high = notes.where((n) => n.priority == NotePriority.high).length;
    final urgent =
        notes.where((n) => n.priority == NotePriority.urgent).length;

    final overdue = notes
        .where((n) =>
            n.dueDate != null &&
            n.dueDate!.isBefore(DateTime.now()) &&
            !n.completed)
        .length;

    final completionRate =
        total > 0 ? (completed / total * 100).toStringAsFixed(1) : '0.0';

    return {
      'total': total,
      'active': active,
      'completed': completed,
      'archived': archived,
      'todos': todos,
      'companyLeads': companyLeads,
      'generalNotes': generalNotes,
      'reminders': reminders,
      'low': low,
      'medium': medium,
      'high': high,
      'urgent': urgent,
      'overdue': overdue,
      'completionRate': completionRate,
    };
  }

  static Map<NoteType, List<NoteItem>> _groupByType(List<NoteItem> notes) {
    final Map<NoteType, List<NoteItem>> grouped = {};
    for (final note in notes) {
      grouped.putIfAbsent(note.type, () => []).add(note);
    }
    for (final entry in grouped.entries) {
      entry.value.sort((a, b) => b.createdAt.compareTo(a.createdAt));
    }
    return grouped;
  }

  static void _writeSummary(
      StringBuffer buffer, Map<String, dynamic> stats, bool isGerman) {
    buffer.writeln(isGerman ? '## Zusammenfassung' : '## Summary');
    buffer.writeln();

    if (isGerman) {
      buffer.writeln(
          'Dieser Bericht enthält eine Übersicht über ${stats['total']} Notizen.');
      buffer.writeln(
          '${stats['active']} sind aktiv, ${stats['completed']} abgeschlossen und ${stats['archived']} archiviert.');
      buffer.writeln();
      buffer
          .writeln('**Abschlussquote:** ${stats['completionRate']}%');
      if ((stats['overdue'] as int) > 0) {
        buffer.writeln();
        buffer.writeln(
            '**Überfällige Einträge:** ${stats['overdue']}');
      }
    } else {
      buffer.writeln(
          'This report contains an overview of ${stats['total']} notes.');
      buffer.writeln(
          '${stats['active']} are active, ${stats['completed']} completed, and ${stats['archived']} archived.');
      buffer.writeln();
      buffer.writeln(
          '**Completion Rate:** ${stats['completionRate']}%');
      if ((stats['overdue'] as int) > 0) {
        buffer.writeln();
        buffer
            .writeln('**Overdue Items:** ${stats['overdue']}');
      }
    }
  }

  static void _writeNotesByType(StringBuffer buffer,
      Map<NoteType, List<NoteItem>> byType, bool isGerman) {
    buffer.writeln(isGerman ? '## Notizen nach Typ' : '## Notes by Type');
    buffer.writeln();

    final typeOrder = [
      NoteType.todo,
      NoteType.companyLead,
      NoteType.reminder,
      NoteType.generalNote,
    ];

    for (final type in typeOrder) {
      final notes = byType[type];
      if (notes == null || notes.isEmpty) continue;

      final label = isGerman ? _getTypeLabelDe(type) : _getTypeLabel(type);
      buffer.writeln('### $label (${notes.length})');
      buffer.writeln();

      switch (type) {
        case NoteType.companyLead:
          buffer.writeln(isGerman
              ? '| Firma | Standort | Lead-Status | Kontakt | Status |'
              : '| Company | Location | Lead Status | Contact | Status |');
          buffer.writeln('|-------|----------|-------------|---------|--------|');
          for (final note in notes) {
            final location = note.location ?? '-';
            final contact = note.contactPerson ?? '-';
            final leadStatus = note.leadStatus != null
                ? (isGerman
                    ? _getLeadStatusLabelDe(note.leadStatus!)
                    : _getLeadStatusLabel(note.leadStatus!))
                : '-';
            final status = isGerman
                ? (note.completed
                    ? '✅ Erledigt'
                    : (note.archived ? '📦 Archiviert' : '📌 Aktiv'))
                : (note.completed
                    ? '✅ Done'
                    : (note.archived ? '📦 Archived' : '📌 Active'));
            buffer.writeln(
                '| ${note.title} | $location | $leadStatus | $contact | $status |');
          }
          break;
        default:
          buffer.writeln(isGerman
              ? '| Titel | Priorität | Fällig | Status |'
              : '| Title | Priority | Due | Status |');
          buffer.writeln('|-------|-----------|--------|--------|');
          for (final note in notes) {
            final priorityIcon = _getPriorityIcon(note.priority);
            final priority = isGerman
                ? _getPriorityLabelDe(note.priority)
                : _getPriorityLabel(note.priority);
            final due = note.dueDate != null
                ? DateFormat('dd.MM.yyyy').format(note.dueDate!)
                : '-';
            final status = isGerman
                ? (note.completed
                    ? '✅ Erledigt'
                    : (note.archived ? '📦 Archiviert' : '📌 Aktiv'))
                : (note.completed
                    ? '✅ Done'
                    : (note.archived ? '📦 Archived' : '📌 Active'));
            buffer.writeln(
                '| ${note.title} | $priorityIcon $priority | $due | $status |');
          }
      }
      buffer.writeln();
    }
  }

  static void _writeAllNotes(
      StringBuffer buffer, List<NoteItem> notes, bool isGerman) {
    buffer.writeln(
        isGerman ? '## Alle Notizen (chronologisch)' : '## All Notes (Chronological)');
    buffer.writeln();

    if (notes.isEmpty) {
      buffer.writeln(
          isGerman ? '*Keine Notizen vorhanden.*' : '*No notes available.*');
      return;
    }

    buffer.writeln(isGerman
        ? '| Erstellt | Typ | Titel | Priorität | Fällig | Status |'
        : '| Created | Type | Title | Priority | Due | Status |');
    buffer.writeln(
        '|----------|-----|-------|-----------|--------|--------|');

    for (final note in notes) {
      final created = DateFormat('dd.MM.yyyy').format(note.createdAt);
      final type =
          isGerman ? _getTypeLabelDe(note.type) : _getTypeLabel(note.type);
      final title = note.title.length > 30
          ? '${note.title.substring(0, 27)}...'
          : note.title;
      final priorityIcon = _getPriorityIcon(note.priority);
      final priority = isGerman
          ? _getPriorityLabelDe(note.priority)
          : _getPriorityLabel(note.priority);
      final due = note.dueDate != null
          ? DateFormat('dd.MM.yyyy').format(note.dueDate!)
          : '-';
      final status = isGerman
          ? (note.completed
              ? '✅ Erledigt'
              : (note.archived ? '📦 Archiviert' : '📌 Aktiv'))
          : (note.completed
              ? '✅ Done'
              : (note.archived ? '📦 Archived' : '📌 Active'));
      buffer.writeln('| $created | $type | $title | $priorityIcon $priority | $due | $status |');
    }
  }

  static void _writeStatistics(
      StringBuffer buffer, Map<String, dynamic> stats, bool isGerman) {
    buffer.writeln(
        isGerman ? '## Statistische Übersicht' : '## Statistical Overview');
    buffer.writeln();

    // Type distribution
    buffer.writeln(
        isGerman ? '### Verteilung nach Typ' : '### Distribution by Type');
    buffer.writeln();
    buffer.writeln(isGerman
        ? '| Typ | Anzahl | Prozent |'
        : '| Type | Count | Percentage |');
    buffer.writeln('|-----|--------|-----------|');

    final total = stats['total'] as int;
    final typeData = [
      ('✅ To-Do', '✅ Aufgabe', stats['todos']),
      ('🏢 Company Lead', '🏢 Firmenkontakt', stats['companyLeads']),
      ('⏰ Reminder', '⏰ Erinnerung', stats['reminders']),
      ('📝 General Note', '📝 Allgemeine Notiz', stats['generalNotes']),
    ];

    for (final (labelEn, labelDe, count) in typeData) {
      final label = isGerman ? labelDe : labelEn;
      final pct = total > 0
          ? ((count as int) / total * 100).toStringAsFixed(1)
          : '0.0';
      buffer.writeln('| $label | $count | $pct% |');
    }

    buffer.writeln();

    // Priority distribution
    buffer.writeln(isGerman
        ? '### Verteilung nach Priorität'
        : '### Distribution by Priority');
    buffer.writeln();
    buffer.writeln(isGerman
        ? '| Priorität | Anzahl | Prozent |'
        : '| Priority | Count | Percentage |');
    buffer.writeln('|-----------|--------|-----------|');

    final priorityData = [
      ('🔴 Urgent', '🔴 Dringend', stats['urgent']),
      ('🟠 High', '🟠 Hoch', stats['high']),
      ('🟡 Medium', '🟡 Mittel', stats['medium']),
      ('🔵 Low', '🔵 Niedrig', stats['low']),
    ];

    for (final (labelEn, labelDe, count) in priorityData) {
      final label = isGerman ? labelDe : labelEn;
      final pct = total > 0
          ? ((count as int) / total * 100).toStringAsFixed(1)
          : '0.0';
      buffer.writeln('| $label | $count | $pct% |');
    }

    buffer.writeln();

    // Overall stats
    buffer.writeln(isGerman ? '### Gesamtstatistik' : '### Overall Statistics');
    buffer.writeln();
    buffer.writeln(isGerman ? '| Kennzahl | Wert |' : '| Metric | Value |');
    buffer.writeln('|----------|------|');
    buffer.writeln(isGerman
        ? '| Notizen gesamt | ${stats['total']} |'
        : '| Total Notes | ${stats['total']} |');
    buffer.writeln(isGerman
        ? '| Aktive Notizen | ${stats['active']} |'
        : '| Active Notes | ${stats['active']} |');
    buffer.writeln(isGerman
        ? '| Abgeschlossene Notizen | ${stats['completed']} |'
        : '| Completed Notes | ${stats['completed']} |');
    buffer.writeln(isGerman
        ? '| Archivierte Notizen | ${stats['archived']} |'
        : '| Archived Notes | ${stats['archived']} |');
    buffer.writeln(isGerman
        ? '| Abschlussquote | ${stats['completionRate']}% |'
        : '| Completion Rate | ${stats['completionRate']}% |');
    buffer.writeln(isGerman
        ? '| Überfällige Einträge | ${stats['overdue']} |'
        : '| Overdue Items | ${stats['overdue']} |');
  }

  // ── Label Helpers ─────────────────────────────────────────────────────

  static String _getTypeLabel(NoteType type) {
    switch (type) {
      case NoteType.todo:
        return 'To-Do';
      case NoteType.companyLead:
        return 'Company Lead';
      case NoteType.generalNote:
        return 'General Note';
      case NoteType.reminder:
        return 'Reminder';
    }
  }

  static String _getTypeLabelDe(NoteType type) {
    switch (type) {
      case NoteType.todo:
        return 'Aufgabe';
      case NoteType.companyLead:
        return 'Firmenkontakt';
      case NoteType.generalNote:
        return 'Allgemeine Notiz';
      case NoteType.reminder:
        return 'Erinnerung';
    }
  }

  static String _getPriorityIcon(NotePriority priority) {
    switch (priority) {
      case NotePriority.low:
        return '🔵';
      case NotePriority.medium:
        return '🟡';
      case NotePriority.high:
        return '🟠';
      case NotePriority.urgent:
        return '🔴';
    }
  }

  static String _getPriorityLabel(NotePriority priority) {
    switch (priority) {
      case NotePriority.low:
        return 'Low';
      case NotePriority.medium:
        return 'Medium';
      case NotePriority.high:
        return 'High';
      case NotePriority.urgent:
        return 'Urgent';
    }
  }

  static String _getPriorityLabelDe(NotePriority priority) {
    switch (priority) {
      case NotePriority.low:
        return 'Niedrig';
      case NotePriority.medium:
        return 'Mittel';
      case NotePriority.high:
        return 'Hoch';
      case NotePriority.urgent:
        return 'Dringend';
    }
  }

  static String _getLeadStatusLabel(LeadStatus status) {
    switch (status) {
      case LeadStatus.researching:
        return '🔍 Researching';
      case LeadStatus.contacted:
        return '📧 Contacted';
      case LeadStatus.applied:
        return '📝 Applied';
      case LeadStatus.interviewing:
        return '💼 Interviewing';
    }
  }

  static String _getLeadStatusLabelDe(LeadStatus status) {
    switch (status) {
      case LeadStatus.researching:
        return '🔍 Recherche';
      case LeadStatus.contacted:
        return '📧 Kontaktiert';
      case LeadStatus.applied:
        return '📝 Beworben';
      case LeadStatus.interviewing:
        return '💼 Im Gespräch';
    }
  }
}
